name: Build and check

on:
  pull_request:
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
  push:
    branches:
      - master
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
        with:
          min-wrapper-count: 2

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
      - name: Build plugin
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: plugin
          arguments: assemble ensureDependenciesAreInlined test --no-daemon
      - name: Save test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-results
          path: plugin/build/reports/tests/test/
      - name: Check plugin codestyle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: plugin
          arguments: ktlintCheck --no-daemon

  check_bashisms:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
      - name: Install checkbashisms
        run: sudo apt-get install -qq devscripts
      - name: Add ktlint git hook
        uses: gradle/gradle-build-action@v2
        with:
          arguments: addKtlintCheckGitPreCommitHook --no-daemon
      - name: Check git bashisms
        run: checkbashisms .git/hooks/pre-commit

  check_samples:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
      - name: Check ktlint-plugin on samples
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck --no-daemon
