name: "New plugin release"
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
  GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
  GITHUB_KEY: ${{ secrets.GithubKey }}

jobs:
  make-new-release:
    name: "Releasing plugin"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
      - uses: gradle/gradle-build-action@v2
      - name: Publish plugin
        run: ./plugin/gradlew -p ./plugin publishPlugins --no-daemon
      - name: Create new Github release
        run: ./plugin/gradlew -p ./plugin githubRelease --no-daemon
